### PR TITLE
Update Android SDK manager dependencies

### LINKED ISSUE #1106: Android SDKManager doesn't run with JDK 17
Substrate runs:
`$GRAALVM_HOME/bin/java ... com.android.sdklib.tool.sdkmanager.SdkManagerCli ...`
With JDK 17, it produces this exception:

```
$JAVA_HOME/bin/java -Dcom.android.sdklib.toolsdir=/home/jpereda/.gluon/substrate/Android/tools -classpath /home/jpereda/.gluon/substrate/Android/tools/lib/*:/home/jpereda/.gluon/substrate/Android/tools/lib/java11/* com.android.sdklib.tool.sdkmanager.SdkManagerCli platforms;android-30
Feb 03, 2022 12:21:32 AM com.sun.xml.bind.v2.runtime.reflect.opt.Injector <clinit>
SEVERE: null
java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:197)
...
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
	at java.base/java.lang.Class.getMethod(Class.java:2227)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:201)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	... 46 more
```

To solve the issue, either update the dependencies, or try the new Command-Line Tools:

https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip

that doesn't need extra dependencies.

### PR DESCRIPTION
**Pull request by jperedadnr**
### Issue

Fixes #1106 

### Progress

- [ ] Change must not contain extraneous whitespace
- [ ] License header year is updated, if required
- [ ] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

**Comment by jperedadnr** [comment]
For now this works, but it is better to move to the command-line tool solution

**Comment by tiainen** [comment]
Does it work with both JDK 11 and 17?

**Review by johanvos — APPROVED** [review]

**Comment by jperedadnr** [comment]
@tiainen yes, works for both 11 and 17, Android sdk and toolchain get installed.

**Review by tiainen — APPROVED** [review]

**Comment by abhinayagarwal** [comment]
JDK 17: https://github.com/abhinayagarwal/hello-gluon-ci/actions/runs/1788911691
JDK 11: https://github.com/abhinayagarwal/hello-gluon-ci/actions/runs/1788949716

**Review by abhinayagarwal — APPROVED** [review]

**Pull request merged**
